version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  reviewers:
  - asmahood
  ignore:
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.21.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.21.0
