version: '3.7'
services:
  test:
    build: .
    command: npm run build:watch
    volumes:
      - .:/usr/app
    depends_on: 
      - db
    environment:
      - DATABASE_URL=postgres://docker:password@db:5432/test_database
    networks:
      - test
  db:
    image: postgres:12.2-alpine
    volumes:
      - ./scripts/create-databases.sh:/docker-entrypoint-initdb.d/create-databases.sh
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=password
      - DATABASES=test
      - DATABASE_ENVS=database
    ports:
      - 5432:5432
    networks:
      - test
networks:
  test:
    external:
      name: test_services_network
